apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../resources/

patches:
  - target:
      kind: CronJob
      name: test-id-annotation
    patch: |-
      - op: replace
        # forward slash is escaped in JSON patches as "~1"
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-id
        value: "annotation-test-id-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-name-annotation
    patch: |-
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-name
        value: "annotation-test-name-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-schedule-change
    patch: |-
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-id
        value: "test-schedule-change-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-cronjob-namespace
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: "${EXTRA_NAMESPACE}"

  - target:
      kind: CronJob
      name: test-group-annotation
    patch: |-
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-id
        value: "test-group-annotation-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-notify-annotation
    patch: |-
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-id
        value: "test-notify-annotation-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-grace-seconds-annotation
    patch: |-
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-id
        value: "test-grace-seconds-annotation-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-id-annotation-multiple-env1
    patch: &multi-anchor |-
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-id
        value: "test-id-annotation-multiple-${RANDOM_ID}"
      - op: replace
        path: /metadata/annotations/k8s.cronitor.io~1cronitor-name
        value: "test-name-annotation-multiple-${RANDOM_ID}"

  - target:
      kind: CronJob
      name: test-id-annotation-multiple-env2
    patch: *multi-anchor
