apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /apiVersion
        value: batch/v1beta1