apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-env-annotation
  annotations:
    k8s.cronitor.io/env: 'environment-test-telemetry'
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args: [/bin/sh, -c, date ; sleep 5 ; echo Hello from k8s]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
