apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-id-annotation-multiple-env1
  annotations:
    k8s.cronitor.io/cronitor-id: ''
    k8s.cronitor.io/cronitor-name: ''
    k8s.cronitor.io/env: 'env1'
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args: [/bin/sh, -c, date ; sleep 5 ; echo Hello from k8s]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid


---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-id-annotation-multiple-env2
  annotations:
    k8s.cronitor.io/cronitor-id: ''
    k8s.cronitor.io/cronitor-name: ''
    k8s.cronitor.io/env: 'env2'
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args: [/bin/sh, -c, date ; sleep 5 ; echo Hello from k8s]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
