apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eventrouter-test-croonjob-excluder
  annotations:
    k8s.cronitor.io/exclude: "true"
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args: [/bin/sh, -c, date ; echo Hello from k8s]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
