{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.rbac.clusterScope "cluster" -}}
kind: ClusterRole
{{ else if eq .Values.rbac.clusterScope "namespace" -}}
kind: Role
{{ else -}}
{{- fail (printf "rbac.clusterScope must be 'cluster' or 'namespace', received '%s'" .Values.rbac.clusterScope) -}}
{{- end -}}
metadata:
  name: {{ include "cronitor-kubernetes-agent.fullname" . }}
  {{- if eq .Values.rbac.clusterScope "namespace" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  labels:
    {{- include "cronitor-kubernetes-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - events
      - pods
      {{- if .Values.config.shipLogs }}
      - pods/log
      {{- end }}
      - namespaces
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
{{- if eq .Values.rbac.clusterScope "cluster" }}
kind: ClusterRoleBinding
{{- else if eq .Values.rbac.clusterScope "namespace" }}
kind: RoleBinding
{{- end }}
metadata:
  {{- if eq .Values.rbac.clusterScope "namespace" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  labels:
    {{- include "cronitor-kubernetes-agent.labels" . | nindent 4 }}
  name: {{ include "cronitor-kubernetes-agent.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if eq .Values.rbac.clusterScope "cluster" }}
  kind: ClusterRole
  {{- else if eq .Values.rbac.clusterScope "namespace" }}
  kind: Role
  {{- end }}
  name: {{ include "cronitor-kubernetes-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cronitor-kubernetes-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end -}}