{{- if .Values.credentials.createSecret.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronitor-kubernetes-agent.fullname" . }}-secret
  labels:
    {{- include "cronitor-kubernetes-agent.labels" . | nindent 4 }}
type: Opaque
data:
  CRONITOR_API_KEY: {{ .Values.credentials.createSecret.apiKey | b64enc }}
{{- end }}