---
apiVersion: v1
kind: Namespace
metadata:
  name: cronitor-mock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-cronitor-api
  namespace: cronitor-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-cronitor-api
  template:
    metadata:
      labels:
        app: mock-cronitor-api
    spec:
      containers:
        - name: mock-server
          image: mock-cronitor-api:latest
          imagePullPolicy: Never  # Use local image loaded into Kind
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /debug/health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /debug/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mock-cronitor-api
  namespace: cronitor-mock
spec:
  selector:
    app: mock-cronitor-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
